version: '3.8'

services:
  web:
    build: .
    container_name: grave_finder_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    restart: always
    environment:
      DB_HOST: gateway01.ap-southeast-1.prod.aws.tidbcloud.com
      DB_PORT: 4000
      DB_NAME: cemetery_db
      DB_USER: ysYpBYbTy8wXRRB.root
      DB_PASS: 9ZRah32Iw1zbNYez